### ISSUE TITLE
a question

### ISSUE THREAD

**Issue by yikyph** [aimi-lab/robust-pose-estimator#2]
Thanks to the you for your work！
But i got some question when i use it.
When i run  `python train_posenet.py`，this will  appear，
ValueError: no calibration file found in ..\data\StereoMIS\H1
And there is no folder named StereoMIS\H1 in StereoMIS,just P1 P2 and
P3.
I downloaded it in https://zenodo.org/record/8154924,is this address right？
Or the train.yaml need to be Revised？
How can i deal with it？

**Comment by mhayoz** [comment]
Alternatively, there is a model trained on the whole StereoMIS dataset here: trained/poseNet_2xf8up4b.pth

**Comment by yikyph** [comment]
oh,thanks for answering, i will try by this way soon.
